name: "Install Dependencies"
description: "Check out the repo, set up Python, and install project requirements."

inputs:
  python-version:
    description: "Python version to use (e.g. 3.11)"
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pip dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
