# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: books-catalog
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: https://github.com/gavilugron/book-catalog.git
#     targetRevision: main
#     path: books-catalog-chart
#     helm:
#       valueFiles:
#         - values.yaml

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
# 