name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/gavilugron/book-catalog
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install yq
        run: |
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq

      - name: Update Helm chart image tag
        run: |
          # Extract the SHA tag for Helm chart
          IMAGE_TAG="${{ github.sha }}"
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" books-catalog-chart/values.yaml

      - name: Commit updated Helm chart
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: bump Helm chart image.tag to ${{ github.sha }}"
          file_pattern: "books-catalog-chart/values.yaml"
          branch: main
