name: CI Deploy

on:
  workflow_run:
    workflows: ["CI Build"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with: { version: 'latest' }

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with: { version: 'latest' }

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig

      - name: Deploy with Helm
        run: |
          helm upgrade --install book-catalog helm/ \
            --kubeconfig kubeconfig \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/book-catalog \
            --set image.tag=latest
