name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: kubectl cluster-info

      - name: Deploy with Helm
        run: |
          helm upgrade --install book-catalog ./books-catalog-chart \
            --namespace default \
            --set image.repository=ghcr.io/gavilugron/book-catalog \
            --set image.tag=${{ github.sha }} \
            --wait \
            --timeout=300s

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/book-catalog -n default --timeout=300s
          kubectl get pods -n default -l app.kubernetes.io/name=books-catalog-chart
